
import "./components.scss"

import CoinImg from "../assets/img/pre-coin.png"

const DescriptionPart = () => {
    return (
        <div className="w-full lg:w-[500px] min-h-[404px] flex flex-col">
            <div className="flex flex-col">
                <div className="text-[42px] md:text-[72px] leading-[79px] text-left">
                    BLOCK AI TOKEN PLATFORM
                </div>
                <div className="text-[#FFFFFFBF] mt-4 text-left">The First AI Utility Project to be developed On-Chain and Launching on Canxium Blockchain. Join the next AI Ecosystem BLOCK AI Core Token!</div>
                <div className="flex flex-col mt-4">
                    <div className="flex flex-row items-start">
                        <img src="/assets/img/check.svg" className="pr-2"/>
                        <div className="text-[#FFFFFFBF] text-left">
                            <span className="font-semibold text-white">Community Governance:</span> Be part of the community core decision maker through BAI VOting Governance.
                        </div>
                    </div>
                    <div className="flex flex-row items-start mt-2.5">
                        <img src="/assets/img/check.svg" className="pr-2"/>
                        <div className="text-[#FFFFFFBF] text-left">
                            <span className="font-semibold text-white">Access To BLOCK AI Products:</span> Get full access to use all BLOCK AI products if you hold certain amount of  BAI Token in you wallet.
                        </div>
                    </div>
                    <div className="flex flex-row items-start mt-2.5">
                        <img src="/assets/img/check.svg" className="pr-2"/>
                        <div className="text-[#FFFFFFBF] text-left">
                            <span className="font-semibold text-white">Revenue Share:</span> Earn part of weekly fees generated by the BLOCK AI products as Airdrop to your wallet holding <span className="text-[#0cafcc]">$BAI</span> as per our revenue share model.
                        </div>
                    </div>
                </div>
            </div>
            <div className="flex flex-col lg:flex-row justify-between">
                <a 
                    href="https://bai.gitbook.io/bai-documentation/" 
                    target="_blank"
                    className="w-[166px] h-[36px] rounded-3xl px-4 py-2 border border-solid mt-6 border-[#0cafcc] text-sm font-medium tracking-tight flex flex-row gap-1 items-center hover:bg-[#0cafcc] hover:text-white"
                >
                    <img src="/assets/img/document.svg"/>
                    Docs
                </a>
                <a 
                    href="https://block.ai/" 
                    target="_blank"
                    className="w-[166px] h-[36px] rounded-3xl px-4 py-2 border border-solid mt-6 border-[#0cafcc] text-sm font-medium tracking-tight flex flex-row gap-1 items-center hover:bg-[#0cafcc] hover:text-white"
                >
                    LAUNCH BLOCK AI
                </a>
            </div>
        </div>
    );
}

export default DescriptionPart;